project_name: nekkus-eye

builds:
  - id: nekkus-eye
    main: ./cmd
    binary: nekkus-eye
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    wrap_in_directory: com.nekkus.eye
    files:
      - src: release_assets/manifest.json
        dst: .
        strip_parent: true

release:
  github:
    owner: GalitskyKK
    name: nekkus-eye
  name_template: "v{{ .Version }}"
